# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in flatito.gemspec
gemspec

gem "minitest", "~> 5.22"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.63", ">= 1.63.0"
gem "rubocop-minitest", "~> 0.35", ">= 0.35.1"
gem "rubocop-performance", "~> 1.21", ">= 1.21.0"
gem "rubocop-rake", "~> 0.6"
