# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in flatito.gemspec
gemspec

gem "minitest", "~> 5.22"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.62"
gem "rubocop-minitest", "~> 0.37", ">= 0.37.1"
gem "rubocop-performance", "~> 1.24", ">= 1.24.0"
gem "rubocop-rake", "~> 0.7", ">= 0.7.0"
