# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in flatito.gemspec
gemspec

gem "minitest", "~> 5.22"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.66", ">= 1.66.0"
gem "rubocop-minitest", "~> 0.35"
gem "rubocop-performance", "~> 1.11"
gem "rubocop-rake", "~> 0.6"
